name: 签到

on:
  push:
  # schedule:
  #   - cron: 0 16 * * *
  workflow_dispatch: # workflow_dispatch 要放最后，否则会导致 schedule 失效

jobs:
  sign-in:
    env:
      WECHAT_PARAMS: ${{ secrets.WECHAT_PARAMS }}
      MOLE_ACCOUNTS: ${{ secrets.MOLE_ACCOUNTS }}
      ECLOUD_ACCOUNT: ${{ secrets.ECLOUD_ACCOUNT }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5
      - name: 安装环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 开始摩尔庄园签到
        run: |
          python3 mole.py
      - name: 开始天翼云盘签到
        run: |
          python3 ecloud.py