name: 签到

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sign-in:
    env:
      WECHAT_PARAMS: ${{ secrets.WECHAT_PARAMS }}
      MOLE_ACCOUNTS: ${{ secrets.MOLE_ACCOUNTS }}
      ECLOUD_ACCOUNT: ${{ secrets.ECLOUD_ACCOUNT }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5
      - name: 安装环境
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      - name: 开始摩尔庄园签到
        run: |
          python mole.py
      - name: 开始天翼云盘签到
        run: |
          python ecloud.py